insert into Credenziali values ("turnoB","dHVybm9C","vigiledelfuoco");
insert into Credenziali values ("capoturno","Y2Fwb3R1cm5v","capoturno");
insert into Vigile values("mail","nome","cognome","B","mansione",0,0,0,true,"grado1","turnoB");
insert into Vigile values("michele73","michele","sica","B","Capo Squadra",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail3","Rosario","Marmo","B","Capo Squadra",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail4","Franco","Mammato","B","Capo Squadra",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail5","Mario","Del Regno","B","Capo Squadra",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail6","Michele","Granato","B","Capo Squadra",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail7","Salvatore","Malaspina","B","Capo Squadra",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail8","Gianluca","Iovino","B","Autista",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail9","Carmine","Sarraino","B","Autista",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail10","Alberto","Barbarulo","B","Autista",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail11","Stefano","Galdi","B","Autista",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail12","Ciro","Fattorusso","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail13","Alfonso","Grieco","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail14","Luca","Raimondi","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail15","Fabrizio","Pepe","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail16","Roberto","Santoro","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail17","Maurizio","Marsano","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail18","Domenico","Giordano","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail19","Ettore","Anzano","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail20","Marzia","Mancuso","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail21","Roberto","Noschese","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail22","Gerardo","Citarella","B","Vigile",0,0,0,true,"grado1","turnoB");
insert into Vigile values("mail23","Modesto","Spedaliere","B","Vigile",0,0,0,true,"grado1","turnoB");